#! /bin/sh

sxhkd &
~/.config/polybar/startup.sh -k $HOME/.config/polybar/config top &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width             1
bspc config window_gap               12

bspc config split_ratio              0.52
bspc config borderless_monocle       true
bspc config gapless_monocle          true
bspc config normal_border_color      "{{base01}}"
bspc config focused_border_color     "{{base03}}"

bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
