#!/usr/bin/env bash
rofi_command="rofi -theme ~/.config/rofi/powermenu.rasi"
uptime=$(uptime -p | sed -e 's/up //g')

# Options
exit=' Exit'
renew=' Refresh'
lock=' Lock'
suspend=' Sleep'
shutdown=' Power Off'

# Variable passed to rofi
options="$lock\n$suspend\n$exit\n$renew\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "$uptime" -dmenu -i)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $lock)
        dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock
        ;;
    $suspend)
        systemctl suspend
        ;;
    $renew)
        kill -HUP $(pidof -s {{window_manager}})
        ;;
    $exit)
        kill -TERM $(pidof -s {{window_manager}})
        ;;
esac
