#!/bin/bash

#xrandr --newmode "2560x1440_33.00"  162.77  2560 2688 2960 3360  1440 1441 1444 1468  -HSync +Vsync &> /dev/null
#xrandr --addmode eDP-1 2560x1440_33.00 &> /dev/null

internal=$(xrandr --current| head -n -1 |grep primary|cut -d' ' -f1)
ext=$(xrandr --current| head -n -1 |grep ' 'connected| grep -v primary | head -n 1| cut -d' ' -f1)
ext2=$(xrandr --current| head -n -1 |grep ' 'connected| grep -v "primary\|${ext}" | head -n 1| cut -d' ' -f1)

undocked() {
    echo -e '1. undocked'
}
docked() {
    echo -e '2. docked'
}
hdmi_external() {
    echo -e '3. hdmi external'
}

print_menu() {
    undocked
    docked
    hdmi_external
}

element_height=1
element_count=3

res=$(print_menu | rofi \
    -dmenu -lines "$element_count" \
    -eh "$element_height" -p 'Select screen setup' -no-custom \
    -width 20 -format i -theme ~/.config/rofi/config)

if [ -z "$res" ] ; then
    exit
fi

case "$res" in
    0)
        xrandr --output $internal --auto --output $ext --off --output $ext2 --off
        ;;
    1)
        xrandr --output $internal --off --output $ext --auto --output $ext2 --auto --right-of $ext
        ;;
    2)
        xrandr --output $internal --auto --output $ext --auto --right-of $internal
        ;;
    *)
        ;;
esac

i3-msg restart &> /dev/null
feh --bg-fill ~/.local/background.jpg
