#!/bin/bash

#echo -e "\n\tUpdating packages"
#echo "----------------------------------------------------"
#sudo apt-get update

#echo -e "\n\tCleaning up old packages"
#echo "----------------------------------------------------"
#sudo apt-get autoremove
#sudo apt-get autoclean

echo -e "\n\tInstalling packages"
echo "----------------------------------------------------"
#sudo apt-get install \
sudo pacman -Sy
    build-essential \
    dkms \
    fonts-font-awesome \
    ttf-font-awesome \
    zsh \
    dconf-cli \
    uuid-runtime \
    python3 \
    python3-pip \
    curl \
    git \
    xsel \
    xclip \
    vim \
    vim-gtk \
    tmux \
    slock \
    ranger \
    python-ueberzug \
    fzf \
    feh \
    cmake \
    rofi

pip3 install --user --requirement requirements.txt

echo -e "\n\tInstalling Oh-My-Zsh"
echo "----------------------------------------------------"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"


echo -e "\n\tGenerating dotfiles"
echo "----------------------------------------------------"
python3 rice_it -o

echo -e "\n\tSetting up Suckless"
echo "----------------------------------------------------"
git clone https://github.com/dapc11/dwm.git
git clone https://github.com/dapc11/st.git

cd dwm
sudo make clean install
cd ../st
sudo make clean install
cd ..
xrdb -merge ~/.Xresources

echo -e "\nSetup Vim - YouCompleteMe by running: \n
cd ~/.vim/plugged/youcompleteme
python3 install.py --all"
echo -e "\nDone"
exit 0
