#!/bin/bash

function install_alacritty
{
    # Install required tools
    sudo apt-get install -y rust cargo cmake libfreetype6-dev libfontconfig1-dev xclip

    # Download, compile and install Alacritty
    git clone https://github.com/jwilm/alacritty
    cd alacritty
    cargo install alacritty

    # Add Man-Page entries
    sudo mkdir -p /usr/local/share/man/man1
    gzip -c extra/alacritty.man | sudo tee /usr/local/share/man/man1/alacritty.1.gz > /dev/null

    # Create desktop file
    cp extra/linux/Alacritty.desktop ~/.local/share/applications/

    # Copy binary to path
    sudo cp ~/.cargo/bin/alacritty /usr/local/bin

    # Use Alacritty as default terminal (Ctrl + Alt + T)
    gsettings set org.gnome.desktop.default-applications.terminal exec 'alacritty'

    # Remove temporary dir
    cd ..
    rm -r alacritty
}

function install_deps
{
    echo -e "\n\tInstalling dependecies"
    echo "----------------------------------------------------"
    #cat .installed.txt | cut -d" " -f1 | xargs sudo pacman -S --noconfirm -q --needed
    for i in $(cat .installed.txt | cut -d" " -f1 | tr "\n" " "); do
      sudo apt-get install -y $i
    done

    sudo apt autoremove

    pip3 install --user --requirement .requirements.txt

    echo -e "\n\tInstalling Oh-My-Zsh"
    echo "----------------------------------------------------"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
}

function setup_fonts
{
    echo -e "\n\tSetting up fonts"
    echo "----------------------------------------------------"
    sudo mkdir -p /usr/local/share/fonts
    sudo cp templates/fonts/* /usr/local/share/fonts
    sudo chmod 777 -R /usr/local/share/fonts
    sudo chown root:root -R /usr/local/share/fonts
    fc-cache -fv
}

function install_kitty
{
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
    ln -s ~/.local/kitty.app/bin/kitty ~/.local/bin/
    cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications
    sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty.desktop
}

function generate_dotfiles
{
    echo -e "\n\tGenerating dotfiles"
    echo "----------------------------------------------------"
    python3 rice_it -t "themes/$1.json" -o
}

function setup_dwm
{
    rm -rf dwm
    git clone https://github.com/dapc11/dwm.git
    cd dwm
    sudo make clean install
    cd ..
}

function setup_st
{
    rm -rf st
    git clone https://github.com/dapc11/st.git
    cd st
    sudo make clean install
    cd ..
}

function setup_suckless
{
    echo -e "\n\tSetting up Suckless"
    echo "----------------------------------------------------"
    setup_dwm
    setup_st
}

function setup_submodules
{
    echo -e "\n\tSetting up Suckless"
    echo "----------------------------------------------------"
    git submodule init
    cd polybar
    ./build.sh
    cd ../../
}

install_deps
setup_fonts
install_alacritty
setup_submodules
generate_dotfiles dapc11
xrdb ~/.Xresources
nitrogen --force-setter=xinerama --set-auto ~/.local/background.jpg
echo -e "Please setup your background with nitrogen."
echo -e "\nDone"
exit 0
