#!/bin/bash
kill $(ps aux | grep 'dunst' | awk '{print $2}') > /dev/null 2>&1
kill $(ps aux | grep 'compton' | awk '{print $2}') > /dev/null 2>&1

dunst -config ~/.config/dunst/dunstrc &> /dev/null &
compton --config  ~/.config/compton/compton.conf &> /dev/null &
xrdb ~/.Xresources
i3-msg restart &> /dev/null
nitrogen --restore
