#!/usr/bin/python3

import argparse
import getpass
import json
import os
import sys
from pathlib import Path
from shutil import copyfile
from distutils.dir_util import copy_tree

import jinja2

class Ricer:
    HOME_DIR = "/home/{0}/{1}"
    EXECUTABLE = True

    def __init__(self, args):
        self.user = getpass.getuser()
        self.should_overwrite = args.overwrite
        self.theme = args.theme

        template_loader = jinja2.FileSystemLoader(searchpath="./templates/")
        self.env = jinja2.Environment(loader=template_loader)
        self.context = self._get_context()

    def _get_context(self):
        with open(self.theme, 'r') as context:
            theme_path = os.path.abspath(self.theme)
            print(f"Using context: '{theme_path}'")
            return json.load(context)

    def _get_destination(self, template, target):
        if self.should_overwrite:
            return Path(target.format(self.user, template))
        return Path(f'output/{template}')

    def render_template(self, template, target='/home/{0}/.config/{1}/', executable=False):
        destination = self._get_destination(template, target)
        if not os.path.exists(destination.parent):
            os.makedirs(destination.parent)

        environment_template = self.env.get_template(template)

        print('Writing to {0}'.format(destination))
        with open(destination, 'w') as destination_file:
            destination_file.write(environment_template.render(self.context))
            if executable:
                mode = os.stat(destination).st_mode
                mode |= (mode & 0o444) >> 2  # copy R bits to X
                os.chmod(destination, mode)

    def copy_file(self, source, target):
        print(f'Copying {source} to {target}')
        if os.path.isdir(source):
            copy_tree(source, target)
        else:
            copyfile(source, target)

def setup_argparser():
    arg_parser = argparse.ArgumentParser(
        prog='rice_it',
        description='Dapc ricer, make your environment consistent from a color perspective.'
    )
    arg_parser.add_argument(
        '--overwrite',
        '-o',
        help='Make rice_it overwrite existing dotfiles in your home directory, use with caution!',
        action='store_true')
    arg_parser.add_argument(
        '-t',
        '--theme',
        action='store',
        dest='theme',
        default='themes/dark.json',
        help='Specify which theme the context will be loaded from. Defaults to dark.json'
    )
    return arg_parser


def main():
    parser = setup_argparser()
    ricer = Ricer(parser.parse_args())
    render_vim(ricer)
    render_rofi(ricer)
    render_utils(ricer)
    render_polybar(ricer)
    render_vs_code(ricer)
    render_awesome(ricer)
    ricer.render_template('alacritty/alacritty.yml')
    ricer.render_template('dunst/dunstrc')
    ricer.render_template('i3/config')
    ricer.render_template('ranger/rc.conf')
    ricer.render_template('compton/compton.conf')
    ricer.render_template('.tmux.conf', Ricer.HOME_DIR)
    ricer.render_template('.zshrc', Ricer.HOME_DIR)
    ricer.render_template('.xprofile', Ricer.HOME_DIR)
    ricer.render_template('.zprofile', Ricer.HOME_DIR)
    ricer.render_template('.Xresources', Ricer.HOME_DIR)
    sys.exit(0)

def render_vim(ricer):
    # ricer.render_template('nvim/init.vim')
    ricer.render_template('.vimrc', ricer.HOME_DIR)
    ricer.render_template('.vimrc', '/home/{0}/.config/nvim/init.vim')

def render_awesome(ricer):
    ricer.render_template('awesome/rc.lua')
    ricer.render_template('awesome/theme.lua')
    background = ricer.context['bg']
    ricer.copy_file(f"templates/images/{background}",
                    f'/home/{ricer.user}/.config/awesome/background.jpg')
    ricer.copy_file('templates/awesome/widgets',
                    f'/home/{ricer.user}/.config/awesome/widgets')
    ricer.copy_file('templates/awesome/icons',
                    f'/home/{ricer.user}/.config/awesome/icons')

def render_vs_code(ricer):
    ricer.render_template('Code/User/settings.json')
    ricer.render_template('Code/User/keybindings.json')

def render_rofi(ricer):
    ricer.render_template('rofi/config.rasi')
    ricer.render_template('rofi/powermenu.rasi')
    ricer.render_template('rofi/rofi-power',
                          '/home/{0}/.config/rofi/rofi-power', Ricer.EXECUTABLE)
    ricer.render_template('rofi/rofi-randr',
                          '/home/{0}/.config/rofi/rofi-randr', Ricer.EXECUTABLE)

def render_polybar(ricer):
    ricer.render_template('polybar/config')
    ricer.render_template('polybar/startup.sh',
                          '/home/{0}/.config/polybar/startup.sh', Ricer.EXECUTABLE)
    ricer.render_template('polybar/updates.sh',
                          '/home/{0}/.config/polybar/updates.sh', Ricer.EXECUTABLE)
    ricer.render_template('polybar/now_playing.py',
                          '/home/{0}/.config/polybar/now_playing.py', Ricer.EXECUTABLE)

def render_utils(ricer):
    ricer.render_template('utils/dimmer',
                          '/home/{0}/.local/bin/dimmer', Ricer.EXECUTABLE)
    ricer.render_template('utils/nightmode',
                          '/home/{0}/.local/bin/nightmode', Ricer.EXECUTABLE)
    ricer.render_template('utils/gita',
                          '/home/{0}/.local/bin/gita', Ricer.EXECUTABLE)


if __name__ == "__main__":
    main()
