#!/usr/bin/python3

import argparse
import getpass
import json
import os
import sys
from pathlib import Path
from shutil import copyfile
from distutils.dir_util import copy_tree
import subprocess

import jinja2

class Ricer:
    EXECUTABLE = True

    def __init__(self, args):
        self.user = getpass.getuser()
        self.overwrite = args.overwrite
        if self.overwrite:
            self.target = f'/home/{self.user}/.config'
        else:
            self.target = f'{os.getcwd()}/target'
        self.theme = args.theme

        template_loader = jinja2.FileSystemLoader(searchpath="./templates/")
        self.env = jinja2.Environment(loader=template_loader)
        self.context = self._get_context()
        self.context['wifi_if'] = self.get_wireless_if()

    def _get_context(self):
        with open(self.theme, 'r') as colors_context:
            theme_path = os.path.abspath(self.theme)
            print(f"Using context: '{theme_path}'")
            with open('themes/settings.json', 'r') as settings_context:
                context = {**json.load(settings_context), **json.load(colors_context)}
                return context

    def _get_destination(self, template):
        dest = f'{self.target}/{template}'
        parent = Path(dest).parent
        if not os.path.exists(parent):
            os.makedirs(parent)
        return dest

    def set_target_dir(self, target):
        self.target = target

    def render_template(self, template, executable=False):
        dest = self._get_destination(template)
        environment_template = self.env.get_template(template)

        print(f'Writing to {dest}')
        with open(dest, 'w') as destination_file:
            destination_file.write(environment_template.render(self.context))
            if executable:
                mode = os.stat(dest).st_mode
                mode |= (mode & 0o444) >> 2  # copy R bits to X
                os.chmod(dest, mode)

    def copy_file(self, source, target):
        print(f'Copying {source} to {target}')
        if os.path.isdir(source):
            copy_tree(source, target)
        else:
            copyfile(source, target)

    def get_wireless_if(self):
        lines = open("/proc/net/wireless", "r").readlines()
        interface = lines[2:][0].split(":")[0]
        print(f'Wireless network interface: {interface}')
        return interface

def setup_argparser():
    arg_parser = argparse.ArgumentParser(
        prog='rice_it',
        description='Dapc ricer, make your environment consistent from a color perspective.'
    )
    arg_parser.add_argument(
        '--overwrite',
        '-o',
        help='Make rice_it overwrite existing dotfiles in your home directory, use with caution!',
        action='store_true')
    arg_parser.add_argument(
        '-t',
        '--theme',
        action='store',
        dest='theme',
        default='themes/dark.json',
        help='Specify which theme the context will be loaded from. Defaults to dark.json'
    )
    return arg_parser


def main():
    parser = setup_argparser()
    ricer = Ricer(parser.parse_args())

    render_vim(ricer)
    render_rofi(ricer)
    if ricer.context['window_manager'] == 'awesome':
        render_awesome(ricer)
    else:
        render_background(ricer)
    render_polybar(ricer)
    render_vs_code(ricer)
    ricer.render_template('alacritty/alacritty.yml')
    ricer.render_template('dunst/dunstrc')
    ricer.render_template('i3/config')
    ricer.render_template('ranger/rc.conf')
    ricer.render_template('compton/compton.conf')
    ricer.render_template('.tmux.conf')
    ricer.render_template('.zshrc')
    ricer.render_template('.xprofile')
    ricer.render_template('.zprofile')
    ricer.render_template('.Xresources')
    render_utils(ricer)
    sys.exit(0)

def render_vim(ricer):
    # ricer.render_template('nvim/init.vim')
    try:
        os.mkdir(f'/home/{ricer.user}/.vim')
    except FileExistsError:
        pass
    ricer.render_template('vim/.vimrc')
    ricer.render_template('vim/mappings.vim')
    ricer.render_template('vim/plugins.vim')
    ricer.render_template('vim/statusline.vim')
    ricer.render_template('vim/fzf.vim')
    ricer.render_template('vim/options.vim')
    ricer.render_template('vim/.vimrc')
    ricer.render_template('vim/dapc11.vim')

def render_awesome(ricer):
    ricer.render_template('awesome/rc.lua')
    ricer.render_template('awesome/theme.lua')
    background = ricer.context['bg']
    ricer.copy_file(f"templates/images/{background}",
                    f'/home/{ricer.user}/.config/awesome/background.jpg')
    ricer.copy_file('templates/awesome/widgets',
                    f'/home/{ricer.user}/.config/awesome/widgets')
    ricer.copy_file('templates/awesome/icons',
                    f'/home/{ricer.user}/.config/awesome/icons')

def render_background(ricer):
    background = ricer.context['bg']
    ricer.copy_file(f"templates/images/{background}",
                    f'/home/{ricer.user}/.local/background.jpg')
    subprocess.run(['feh', '--bg-fill', f'/home/{ricer.user}/.local/background.jpg'])

def render_vs_code(ricer):
    ricer.render_template('Code/User/settings.json')
    ricer.render_template('Code/User/keybindings.json')

def render_rofi(ricer):
    ricer.render_template('rofi/config.rasi')
    ricer.render_template('rofi/powermenu.rasi')
    ricer.render_template('rofi/rofi-power', Ricer.EXECUTABLE)
    ricer.render_template('rofi/rofi-randr', Ricer.EXECUTABLE)

def render_polybar(ricer):
    ricer.render_template('polybar/config')
    ricer.render_template('polybar/startup.sh', Ricer.EXECUTABLE)
    ricer.render_template('polybar/updates.sh', Ricer.EXECUTABLE)
    ricer.render_template('polybar/now_playing.py', Ricer.EXECUTABLE)

def render_utils(ricer):
    ricer.set_target_dir(f'/home/{ricer.user}/.local')
    ricer.render_template('bin/dimmer', Ricer.EXECUTABLE)
    ricer.render_template('bin/nightmode', Ricer.EXECUTABLE)
    ricer.render_template('bin/gita', Ricer.EXECUTABLE)


if __name__ == "__main__":
    main()
