#!/usr/bin/env sh

rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/dart-flutter.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/yii.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/cuda.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/sass.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/progress.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/supercollider.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/scheme.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/lpc.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/yii-chtml.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/simplemvcf.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/ruby.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/laravel.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/diff.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/matlab.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/twig.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/kotlin.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/html.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript-jasmine.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/fsharp.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/make.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/jsp.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/haml.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript-openui5.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/processing.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/c.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/coffee
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/coffee/jquery_coffee.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/coffee/coffee.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/coffee/requirejs_coffee.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/coffee/angular_coffee.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript-mocha.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/alpaca.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/htmltornado.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/vue.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/haskell.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/elm.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/fortran.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/cpp.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/racket.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/octave.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/tex.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/chef.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript-d3.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/perl.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/textile.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/ocaml.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/autoit.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/falcon.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/d.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/verilog.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/tcl.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/slim.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/clojure.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/scala.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/rust.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript-bemjson.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/liquid.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/openfoam.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/actionscript.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/cmake.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/vhdl.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/phoenix.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/stylus.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/reason.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/django.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/objc.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/eelixir.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/jade.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/mako.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/rmd.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/css.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript/javascript-requirejs.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript/javascript-react.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript/javascript.node.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript/javascript-jquery.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript/javascript-redux.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/javascript/javascript.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/handlebars.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/svelte.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/perl6.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/erlang.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/eruby.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/systemverilog.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/ada.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/arduino.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/snippets.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/r.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/rst.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/php.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/plsql.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/sql.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/idris.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/purescript.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/lfe.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/julia.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/puppet.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/rails.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/pandoc.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/po.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/scss.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/typescript.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/xslt.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/htmldjango.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/_.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/typescriptreact.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/ls.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/apache.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/codeigniter.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/ledger.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/elixir.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/freemarker.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/cs.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/ps1.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/dosini.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/dart.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/snippets/crystal.snippets


rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/ada.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/all.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/bib.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/bindzone.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/blade.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/coffee-jasmine.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/coffee-react.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/coffee.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/cpp.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/crystal.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/c.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/cs.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/css.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/cuda.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/django.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/d.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/eelixir.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/ejs.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/elm.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/erlang.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/eruby.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/haskell.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/help.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/htmldjango.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/htmljinja.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/html_minimal.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/html.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/javascript-angular.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/javascript-ember.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/javascript-jasmine-arrow.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/javascript-jsdoc.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/javascript-node.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/javascript_react.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/javascript.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/json.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/julia.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/ledger.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/lhaskell.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/lua.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/mako.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/markdown.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/matlab.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/objc.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/ocaml.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/octave.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/pandoc.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/perl.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/php-laravel.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/php-phpspec.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/php.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/php-symfony2.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/plsql.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/proto.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/puppet.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/python.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/rails.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/rnoweb.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/robot.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/r.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/rst.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/ruby.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/rust.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/sh.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/snippets.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/soy.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/supercollider.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/svelte.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/tcl.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/texmath.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/tex.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/typescript_react.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/typescript.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/vim.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/vue.snippets
rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/xhtml.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/xml.snippets
# rm -rf ~/.config/nvim/plugged/vim-snippets/UltiSnips/zsh.snippets
