if require "user.first_load"() then
  return
end
require("user.options")
require("user.plugins")
require("user.keymaps")
require("user.fzf")
require("user.autopairs")
-- require("user.colorizer")
require("user.filetype")
require("user.gitsigns")
require("user.indent_blankline")
-- require("user.lint")
require("user.lsp_config")
require("user.lualine")
require("user.nvim_cmp")
require("user.nvim_comment")
require("user.nvim_tree")
-- require("user.telekasten")
require("user.telescope")
require("user.toggleterm")
require("user.treesitter")
