#!/bin/bash

internal=eDP-1
ext=DP-2-1
ext2=DP-2-2
ext3=HDMI-1

xrandr --newmode "2560x1440_33.00"  162.77  2560 2688 2960 3360  1440 1441 1444 1468  -HSync +Vsync
xrandr --addmode eDP-1 2560x1440_33.00

internal=$(xrandr|grep primary|cut -d' ' -f1)
# ext=$(xrandr |grep ' 'connected| grep -v primary | head -n 1| cut -d' ' -f1)
# ext2=$(xrandr |grep ' 'connected| grep -v primary | tail -n 1| cut -d' ' -f1)

external_off() {
cat <<EOF
Undocked
┏━━━━┓          External monitor disabled - $ext
┃    ┃          External monitor disabled - $ext2
┗━━━━┛          Internal monitor enabled  - $internal
EOF
}
internal_off() {
cat <<EOF
Docked
┏━━━━┓ ┏━━━━┓   External monitor enabled  - $ext
┃    ┃ ┃    ┃   External monitor enabled  - $ext2
┗━━━━┛ ┗━━━━┛   Internal monitor disabled - $internal
EOF
}
presentation() {
cat <<EOF
Presentation
┏━━━━┓ ┏━━━━┓   External monitor enabled - $ext3
┃    ┃ ┃    ┃   Internal monitor enabled - $internal
┗━━━━┛ ┗━━━━┛
EOF
}

print_menu() {
external_off
echo -e '\0'
internal_off
echo -e '\0'
presentation
}

element_height=5
element_count=3

res=$(print_menu | rofi \
    -dmenu -sep '\0' -lines "$element_count" \
    -eh "$element_height" -p '' -no-custom \
    -format i -theme ~/.config/rofi/screen)

if [ -z "$res" ] ; then
    exit
fi

case "$res" in
    0)
        #xrandr --output $internal --mode 2560x1440_33.00 --output $ext --off --output $ext2 --off
        xrandr --output $internal --auto --output $ext --off --output $ext2 --off --output $ext3 --off
        ;;
    1)
        xrandr --output $internal --off --output $ext --auto --output $ext2 --auto --right-of $ext --output $ext3 --off
        ;;
    2)
        xrandr --output $internal --auto --output $ext3 --auto --right-of $internal
        ;;
    *)
        ;;
esac
