[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
shebangs = ["python"]
roots = []
comment-token = "#"
language-server = { command = "pylsp" }
indent = { tab-width = 4, unit = "    " }
auto-format = true
formatter = { command = "sh", args = ["-c", "black --quiet - | isort -"]}

[language.config.pylsp.plugins]
flake8 = {enabled = true}
autopep8 = {enabled = true}
mccabe = {enabled = true}
pycodestyle = {enabled = true}
pyflakes = {enabled = true}
pylint = {enabled = true}
yapf = {enabled = false}
ruff = {enabled = false}

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python3"
args = ["-m", "debugpy"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "{0}" }

[[language]]
name = "java"
language-server = { command = "jdtls", args = ["-data", "~/.cache/jdtls/my_project"] }