[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", ".git"]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
auto-format = true
formatter = { command = "black", args = ["-", "-q"] }

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python"
args = ["-m", "debugpy"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [ { name = "entrypoint", completion = "filename", default = "." } ]
args = { mode = "debug", program = "{0}" }

[[language]]
name = "java"
language-server = { command = "jdtls", args = ["-data", "~/.cache/jdtls/my_project"] }
