#!/usr/bin/python
import sys
import subprocess
import argparse


def run(command):
    return subprocess.Popen(command, shell=True, stdout=subprocess.PIPE).stdout.read()


parser = argparse.ArgumentParser()
parser.add_argument("-i", action='store_true')
parser.add_argument("-d", action='store_true')
args = parser.parse_args()

try:
    with open("/tmp/.dapc_brightness", "r") as brightness_file:
        current_brightness = float(brightness_file.readlines()[0].replace('\n', ''))
        if current_brightness < 1 or current_brightness > 0.1:
            display_name = run('xrandr | grep " connected" |  cut -f1 -d" "').replace('\n', '')

            if args.i:
                current_brightness += 0.1
        if args.d:
            current_brightness -= 0.1

        if (current_brightness > 0.9 and args.i) or (current_brightness < 0 and args.d):
            sys.exit(1)
        run('xrandr --output {0} --brightness {1}'.format(display_name, current_brightness + 0.1))
        print(current_brightness)
except IOError:
    current_brightness = 1

with open("/tmp/.dapc_brightness", "w+") as brightness_file:
    brightness_file.write(str(current_brightness))
sys.exit(0)
