#!/bin/bash

source ~/.local/lib/functions.sh
is_in_git_repo || return
git branch -a --color=always | grep -v '/HEAD\s' | sort |\
fzf-down --ansi --multi --tac --preview-window right:70% \
  --preview 'git log --oneline --graph --date=short --color=always --pretty="format:%C(auto)%cd %h%d %s" $(sed s/^..// <<< {} | cut -d" " -f1)' |\
sed 's/^..//' | cut -d' ' -f1 |\
sed 's#^remotes/##'
