#!/bin/bash

source ~/.local/lib/functions.sh
is_in_git_repo || return
git remote -v | awk '{print $1 "\t" $2}' | uniq |\
fzf-down --tac \
  --preview 'git log --oneline --graph --date=short --pretty="format:%C(auto)%cd %h%d %s" {1}' |\
cut -d$'\t' -f1
