#!/bin/bash

index=$(pacmd list-cards | grep index | tail -1 | xargs | cut -d" " -f 2)

if [[ "${1}" == "teams" ]]; then
  pactl set-card-profile "${index}" headset_head_unit
else
  pactl set-card-profile "${index}" a2dp_sink
fi
