#!/bin/bash

cols=$(( COLUMNS / 3 ))
sep='{::}'

cp -f ~/.config/google-chrome/Default/History /tmp/h

sqlite3 -separator $sep /tmp/h \
    "select substr(title, 1, $cols), url from urls order by last_visit_time desc" |
    awk -F $sep '{printf "%-'$cols's  %s\n", $1, $2}' | grep -v "file" |
    fzf --ansi --multi | sed 's#.*\(https*://\)#\1#' | xargs -I {} xdg-open "{}"
