#!/bin/bash -x

# set up the two monitors for bspwm
# NOTE This is a simplistic approach because I already know the settings I
# want to apply.
ext_monitor_status=$(xrandr --query | grep 'HDMI-1')
if [[ ${ext_monitor_status} == *"HDMI-1 connected"* ]]; then
    xrandr --output eDP-1 --primary -s 1920x1080 --rotate normal --output HDMI-1 -s 2560x14400 --rotate normal --right-of eDP-1
else
    xrandr --output eDP-1 --primary -s 1920x1080 --rotate normal
fi
