#!/usr/bin/python3

import os
import subprocess as sp
from subprocess import PIPE
import getpass
from subprocess import check_output

def get_pid(name):
    return check_output(["pidof", "-s", name])

if __name__ == '__main__':

    user = getpass.getuser()
    dwm_pid = get_pid("dwm").decode("utf-8")
    commands = {
        ' Exit':       "kill -TERM {}".format(dwm_pid),
        '♻ Renew dwm':  "kill -HUP {}".format(dwm_pid),
        ' Lock':       'slock',
        ' Suspend':    'systemctl suspend',
        ' Hibernate':  'systemctl hibernate',
        ' Reboot':     'systemctl reboot',
        ' Shutdown':   'systemctl poweroff',
    }

    options = commands.keys()
    title = 'rofi-power'
    rofi = f'rofi -dmenu -i -theme /home/{user}/.config/rofi/config -lines 6 -width 20 -p {title}'.split()
    rofi_input = '\n'.join(x for x in options)

    cp = sp.run(rofi, input=rofi_input, encoding='utf-8', stdout=PIPE, stderr=PIPE)
    if not cp.returncode:
        selection = cp.stdout.strip()
        if selection in commands:
            sp.run(commands[selection].split())
