#!/usr/bin/python3

import os
import subprocess as sp
from subprocess import PIPE
import getpass

if __name__ == '__main__':

    user = getpass.getuser()
    commands = {
        ' Exit':       'kill -TERM $(pidof -s DWM)',
        '♻ Renew dwm':  'kill -HUP $(pidof -s DWM)',
        ' Lock':       'slock',
        ' Suspend':    'systemctl suspend',
        ' Hibernate':  'systemctl hibernate',
        ' Reboot':     'systemctl reboot',
        ' Shutdown':   'systemctl poweroff',
    }

    options = commands.keys()
    title = 'rofi-power'
    rofi = f'rofi -dmenu -i -theme /home/{user}/.config/rofi/config -lines 6 -width 20 -p {title}'.split()
    rofi_input = '\n'.join(x for x in options)

    cp = sp.run(rofi, input=rofi_input, encoding='utf-8', stdout=PIPE, stderr=PIPE)
    if not cp.returncode:
        selection = cp.stdout.strip()
        if selection in commands:
            sp.run(commands[selection].split())
