require("aerial").setup{
    backends = { "lsp", "treesitter", "markdown" },
    close_behavior = "auto",
    default_bindings = true,
    default_direction = "prefer_right",
    disable_max_lines = 10000,
    filter_kind = {
        "Class",
        "Constructor",
        "Enum",
        "Function",
        "Interface",
        "Module",
        "Method",
        "Struct",
    },
    highlight_mode = "split_width",
    highlight_closest = true,
    highlight_on_jump = 300,
    ignore = {
        unlisted_buffers = true,
        filetypes = {},
        buftypes = "special",
        wintypes = "special",
    },
    link_folds_to_tree = true,
    link_tree_to_folds = true,
    manage_folds = true,
    max_width = { 100, 0.5 },
    width = nil,
    min_width = 35,
    nerd_font = "auto",
    on_attach = nil,
    open_automatic = false,
    placement_editor_edge = false,
    post_jump_cmd = "normal! zz",
    close_on_select = false,
    show_guides = false,
    update_events = "TextChanged,InsertLeave",
    guides = {
        mid_item = "├─",
        last_item = "└─",
        nested_top = "│ ",
        whitespace = "  ",
    },
    float = {
        border = "single",
        relative = "cursor",
        max_height = 0.9,
        height = nil,
        min_height = { 8, 0.1 },
        override = function(conf)
            return conf
        end,
    },
    treesitter = {
        update_delay = 150,
    },
    markdown = {
        update_delay = 300,
    },
}
